CREATE TABLE Actor
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    age  INT CHECK ( age > 0 )
);

CREATE TABLE Movie
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
year_of_production INT CHECK ( year_of_production > 1900 )
);

-- Создаём связывающую таблицу (Join Table)

CREATE TABLE Actor_Movie(
    actor_id INT REFERENCES Actor(id),
    movie_id int REFERENCES Movie(id),
    PRIMARY KEY (actor_id,movie_id)
)