CREATE TABLE Person
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age  INT CHECK ( age < 100 )
);

DROP TABLE item;
CREATE TABLE Item
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    item_name  varchar(100) NOT NULL
);

INSERT INTO person(name, age) VALUES ('Tom',35);
INSERT INTO person(name, age) VALUES ('Bob',37);
INSERT INTO person(name, age) VALUES ('Katy',39);

INSERT INTO item(person_id, item_name) VALUES (1,'Book');
INSERT INTO item(person_id, item_name) VALUES (1,'AirPods');
INSERT INTO item(person_id, item_name) VALUES (2,'Iphone');
INSERT INTO item(person_id, item_name) VALUES (3,'Kindle');
INSERT INTO item(person_id, item_name) VALUES (3,'TV');
INSERT INTO item(person_id, item_name) VALUES (3,'PlayStation');