CREATE TABLE Person
(
    id   INT PRIMARY KEY,
    name VARCHAR(100),
    age  INT
);

INSERT INTO person (id, name, age)
VALUES (1, 'Test person', 20);

DROP TABLE person;

CREATE TABLE Person
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(100),
    age  INT
);
